using FluentMigrator;

namespace SagiCore.Infrastructure.Migrations.Versions
{
    [Migration(DatabaseVersion.TABELA_PRODUTO, "Criação das tabelas de produto, pedido de venda e itens do pedido de venda")]
    public class Version0000001 : Migration
    {
        public override void Down()
        {
            throw new NotImplementedException();
        }

        public override void Up()
        {
            Create.Table("cag_pro")
                .WithColumn("codpro").AsString(6).NotNullable().WithDefaultValue("")
                .WithColumn("produto").AsString(120).NotNullable().WithDefaultValue("")
                .WithColumn("produto_complemento").AsString(500).NotNullable().WithDefaultValue("")
                .WithColumn("subcod").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("subprod").AsString(6).NotNullable().WithDefaultValue("")
                .WithColumn("un").AsString(3).NotNullable().WithDefaultValue("")
                .WithColumn("codcat").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("nomeest").AsString(255).NotNullable().WithDefaultValue("")
                .WithColumn("comrec").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("codref1").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("codref2").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("codref3").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("codref4").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("codref5").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("ncm").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("empresa").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("peso_pro").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("peso_teorico").AsDecimal(19, 8).NotNullable().WithDefaultValue(0)
                .WithColumn("tp_prod").AsString(2).NotNullable().WithDefaultValue("")
                .WithColumn("md_precom").AsDecimal(19, 9).NotNullable().WithDefaultValue(0)
                .WithColumn("md_preven").AsDecimal(19, 9).NotNullable().WithDefaultValue(0)
                .WithColumn("bonus_prc").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("lotpad").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("taxa_conv").AsDecimal(6, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("altura").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("comprimento").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("largura").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_min1").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_max1").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_min2").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_max2").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_min3").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_max3").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_min4").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_max4").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("peso_acima").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("prc_acima").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("peso_ac2").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("prc_ac2").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("peso_baixo").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("prc_baixo").AsDecimal(15, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("aprovaped").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("usefis").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("codfis").AsString(6).NotNullable().WithDefaultValue("")
                .WithColumn("subfis").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("ult_data").AsDate().Nullable()
                .WithColumn("obs").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("diverso").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("rendimento").AsDecimal(5, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("cod_barras").AsString(255).NotNullable().WithDefaultValue("")
                .WithColumn("tipo_barras").AsString(30).NotNullable().WithDefaultValue("")
                .WithColumn("id_onu").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("status").AsString(7).NotNullable().WithDefaultValue("")
                .WithColumn("codcdc").AsString(20).NotNullable().WithDefaultValue("")
                .WithColumn("bloq_inventario").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("mix_venda").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("nao_obriga_mtr").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("ativo_saida_ins").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("cor_producao").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("usacompetencia").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("editavalorcusto").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("usoprecocusto").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("tabela_servicos_codigo").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("nao_movimentar").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("dias_uso").AsInt32().Nullable()
                .WithColumn("cad_usuario").AsString(25).Nullable()
                .WithColumn("cad_data").AsDate().Nullable()
                .WithColumn("pes_avulsa_serv").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("obriga_os_saida_ins").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("tipo_pesquisa").AsString(10).Nullable()
                .WithColumn("id_subcategoria").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("epi_com_ca").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("epi_tamanho").AsString(10).Nullable()
                .WithColumn("liga").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("tipo_liga").AsString(4).NotNullable().WithDefaultValue("")
                .WithColumn("solicitar_metragem_class").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("codigo_epi").AsInt64().NotNullable().WithDefaultValue(0)
                .WithColumn("validade_epi").AsDate().Nullable()
                .WithColumn("descricao_alternativa_exp").AsString(120).NotNullable().WithDefaultValue("")
                .WithColumn("fator_conv_ex").AsDecimal(19, 5).NotNullable().WithDefaultValue(0)
                .WithColumn("un_trib_ex").AsString(3).NotNullable().WithDefaultValue("")
                .WithColumn("cat8309").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("tecnologia").AsString(120).NotNullable().WithDefaultValue("")
                .WithColumn("usar_mtr").AsBoolean().NotNullable().WithDefaultValue(false);

            Create.Table("pedido_ven")
                .WithColumn("pednum").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("dataped").AsDate().NotNullable()
                .WithColumn("dataval").AsDate().NotNullable()
                .WithColumn("codcli").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("cliente").AsString(60).NotNullable().WithDefaultValue("")
                .WithColumn("codvnd").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("vendedor").AsString(60).NotNullable().WithDefaultValue("")
                .WithColumn("impnumped").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("imppedcli").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("obsfiscal1").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("prazo_ent").AsDate().NotNullable()
                .WithColumn("obs").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("ende_entre").AsString(60).NotNullable().WithDefaultValue("")
                .WithColumn("num_entre").AsString(15).NotNullable().WithDefaultValue("")
                .WithColumn("bai_entre").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("cid_entre").AsString(35).NotNullable().WithDefaultValue("")
                .WithColumn("ibge_entre").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("uf_entre").AsString(2).NotNullable().WithDefaultValue("")
                .WithColumn("cep_entre").AsString(8).NotNullable().WithDefaultValue("")
                .WithColumn("cod_pais_entre").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("aprovado").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("usuario").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("data").AsDate().NotNullable()
                .WithColumn("hora").AsString(8).NotNullable().WithDefaultValue("")
                .WithColumn("status").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("empresa").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("vlrfrete").AsDecimal(17, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("pedcli").AsString(20).NotNullable().WithDefaultValue("")
                .WithColumn("itemped").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("naogernf").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("use_aprova").AsString(30).NotNullable().WithDefaultValue("")
                .WithColumn("data_aprova").AsDate().NotNullable()
                .WithColumn("embarque").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("revisar").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("seguro").AsDecimal(17, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("vlrservicos").AsDecimal(17, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("volumes").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("tipovol").AsString(15).NotNullable().WithDefaultValue("")
                .WithColumn("moeda").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("motivo_alt").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("user_alt").AsString(30).NotNullable().WithDefaultValue("")
                .WithColumn("unidade").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("compl_entre").AsString(60).NotNullable().WithDefaultValue("")
                .WithColumn("beneficiamento").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("encerra_aomov").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("codcli_destino").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("codtransp_destino").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("hora_aprova").AsString(8).NotNullable().WithDefaultValue("")
                .WithColumn("ped_tip_terc").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("ped_cod_terc").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("ped_assume_cfop").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("nr_tentativa_rec").AsInt16().NotNullable().WithDefaultValue(0)
                .WithColumn("numorc").AsInt64().NotNullable().WithDefaultValue(0)
                .WithColumn("ped_scrap").AsString(20).NotNullable().WithDefaultValue("")
                .WithColumn("visto_tabela_comissao").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("usuario_tabela_comissao").AsString(30).NotNullable().WithDefaultValue("")
                .WithColumn("pedido_global").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("consignado").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("tipo_boleto").AsString(25).NotNullable().WithDefaultValue("");

            Create.Table("pediten_v")
                .WithColumn("pednum").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("dataped").AsDate().NotNullable()
                .WithColumn("codcli").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("codpro").AsString(6).NotNullable().WithDefaultValue("")
                .WithColumn("subcod").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("produto").AsString(120).NotNullable().WithDefaultValue("")
                .WithColumn("un").AsString(3).NotNullable().WithDefaultValue("")
                .WithColumn("peso").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco").AsDecimal(16, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("preco_nf").AsDecimal(16, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("total").AsDecimal(17, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("frete").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("prazo").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("condicao").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("condicao_pf").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("vlrdesconto").AsDecimal(17, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("com_icms").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("icms").AsDecimal(5, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("ipi").AsDecimal(5, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("totipi").AsDecimal(15, 2).NotNullable().WithDefaultValue(0)
                .WithColumn("cfop").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("cfop_id").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("cst").AsString(3).NotNullable().WithDefaultValue("")
                .WithColumn("pedcli").AsString(20).NotNullable().WithDefaultValue("")
                .WithColumn("itemped").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("bloqueia").AsBoolean().NotNullable().WithDefaultValue(false)
                .WithColumn("peso_carga").AsDecimal(18, 4).NotNullable().WithDefaultValue(0)
                .WithColumn("usuario").AsString(25).NotNullable().WithDefaultValue("")
                .WithColumn("data").AsDate().NotNullable()
                .WithColumn("hora").AsString(8).NotNullable().WithDefaultValue("")
                .WithColumn("status").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("obs_fiscal").AsString(50).NotNullable().WithDefaultValue("")
                .WithColumn("empresa").AsString(10).NotNullable().WithDefaultValue("")
                .WithColumn("obs_iten").AsString(int.MaxValue).NotNullable().WithDefaultValue("") // Memo
                .WithColumn("codcdc").AsString(20).NotNullable().WithDefaultValue("")
                .WithColumn("trib_id").AsInt32().NotNullable().WithDefaultValue(0)
                .WithColumn("descricao_process").AsString(100).NotNullable().WithDefaultValue("")
                .WithColumn("cond_frete").AsString(1).NotNullable().WithDefaultValue("")
                .WithColumn("centro_id").AsInt32().NotNullable().WithDefaultValue(0);
        }
    }
}
